name: Code Coverage

on:
    push: ~
    pull_request: ~

jobs:
    coverage:
        name: Lowest deps
        runs-on: ubuntu-latest
        steps:
            -   name: Set up PHP
                uses: shivammathur/setup-php@2.9.0
                with:
                    php-version: 7.4
                    coverage: pcov

            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Download dependencies
                run: composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable --prefer-lowest

            -   name: Run tests
                run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

            -   name: Scrunitizer CI
                run: |
                    wget https://scrutinizer-ci.com/ocular.phar
                    php ocular.phar code-coverage:upload --format=php-clover coverage.xml
