name: Tests

on:
    push: ~
    pull_request: ~

jobs:
    php:
        strategy:
            matrix:
                php-versions: [ '7.4', '8.0' ]

        runs-on: 'ubuntu-latest'

        steps:

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    tools: none

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: PHP Unit Tests
                run: vendor/bin/phpunit
